services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"
      - "29092:29092"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: logrider
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./persist/init-clickhouse.sql:/docker-entrypoint-initdb.d/init-clickhouse.sql

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: logrider
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logrider
    ports:
      - "5432:5432"
    volumes:
      - ./persist/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  benthos-pipeline:
    image: jeffail/benthos:latest
    environment:
      CLICKHOUSE_DSN: "clickhouse://default:password@clickhouse:9000/logrider"
    volumes:
      - ./pipelines/unified.yaml:/benthos.yaml
    depends_on:
      - redpanda
      - redis
      - clickhouse
    command: -c /benthos.yaml

  benthos-persist:
    image: jeffail/benthos:latest
    environment:
      CLICKHOUSE_DSN: "clickhouse://default:password@clickhouse:9000/logrider"
    volumes:
      - ./pipelines/persist.yaml:/benthos.yaml
    depends_on:
      - redpanda
      - redis
      - clickhouse
    command: -c /benthos.yaml

  alert-worker:
    build: ./workers/alert
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379



  classifier-worker:
    build: ./workers/classifier
    depends_on:
      - redpanda
      - redis
      - clickhouse
    environment:
      REDIS_URL: redis://redis:6379
      REDPANDA_BROKERS: redpanda:29092
      CLICKHOUSE_URI: http://clickhouse:8123/?user=default&password=password

  web-server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - redpanda
      - clickhouse
      - postgres
    environment:
      SERVER_PORT: 3000
      REDPANDA_BROKERS: redpanda:29092
      REDIS_URL: redis://redis:6379
      CLICKHOUSE_URI: http://clickhouse:8123/?user=default&password=password
      POSTGRES_URI: postgres://logrider:password@postgres:5432/logrider
