input:
  kafka:
    addresses:
      - redpanda:29092
    topics:
      - logrider.alerts.candidate-detected.v1
    consumer_group: "logrider.realtime.alert-forwarder.v1"

pipeline:
  processors:
    - mapping: |
        root.type = "ALERT_STREAM"
        root.log = this

output:
  redis_pubsub:
    url: redis://redis:6379
    channel: logrider:realtime:alert-events
