input:
  kafka:
    addresses:
      - ${REDPANDA_BROKERS}
    topics:
      - ${KAFKA_TOPIC_ALERT_CANDIDATES}
    consumer_group: "${KAFKA_GROUP_ALERT_REALTIME_FORWARDER}"

pipeline:
  processors:
    - mapping: |
        root.type = "ALERT_STREAM"
        root.log = this

output:
  redis_pubsub:
    url: ${REDIS_URL}
    channel: ${REDIS_CHANNEL_ALERT_REALTIME}
