input:
  kafka:
    addresses:
      - redpanda:29092
    topics:
      - logs-persist
    consumer_group: "logrider_persist"

buffer:
  memory:
    limit: 67108864
    batch_policy:
      count: 2000
      period: "250ms"
    # batch_policy:
    #   count: 500
    #   period: "1s"

pipeline:
  processors:
    - branch:
        request_map: 'root = this'
        processors:
          - archive:
              format: lines
          - http:
              url: "http://clickhouse:8123/?query=INSERT%20INTO%20logrider.logs_enriched%20FORMAT%20JSONEachRow&async_insert=1&wait_for_async_insert=1&user=${CLICKHOUSE_USER:default}&password=${CLICKHOUSE_PASSWORD:password}"
              verb: POST
              headers:
                Content-Type: application/x-ndjson
        result_map: 'root = this'

output:
  switch:
    cases:
      - check: errored()
        output:
          kafka:
            addresses:
              - redpanda:29092
            topic: dlq-clickhouse
      - output:
          redis_pubsub:
            url: redis://redis:6379
            channel: ws-events
          processors:
            - mapping: |
                root = this
                root.Status = "Persisted"
